name: Deploy to Google Cloud Run
on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  deploy:
    name: Deploy to GCP Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}

      - name: Authenticate Docker to GCP
        run: |
          echo ${GCLOUD_SA_KEY} | gcloud auth activate-service-account --key-file=-
          gcloud auth configure-docker gcr.io

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/${{ secrets.GCLOUD_SERVICE_NAME }} -f server/api/Dockerfile .

      - name: Push Docker image to Google Container Registry
        run: |
          docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/${{ secrets.GCLOUD_SERVICE_NAME }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.GCLOUD_SERVICE_NAME }} \
          --image gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/${{ secrets.GCLOUD_SERVICE_NAME }} \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated \
          --set-env-vars CLOUD_SQL_CONNECTION_NAME=${{ secrets.GCLOUD_SQL_CONNECTION_NAME }} \
          --set-env-vars DB_USER=${{ secrets.GCLOUD_DB_USER }} \
          --set-env-vars DB_PASSWORD=${{ secrets.GCLOUD_DB_PASSWORD }} \
          --set-env-vars DB_NAME=${{ secrets.GCLOUD_DB_NAME }} \
          --add-cloudsql-instances ${{ secrets.GCLOUD_SQL_CONNECTION_NAME }}