name: Deploy to Google Cloud Run
on:
  push:
    branches:
      - main
    

jobs:
  deploy:
    name: Deploy to GCP Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: paper-lobster
          install_components: 'beta'

      - name: Authenticate Docker to GCP
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Print Docker Info
        run: docker info
        
      - name: Build Docker image
        run: |
          docker build -t europe-west1-docker.pkg.dev/paper-lobster/paper-shop-repo/paper-shop-api-server:latest -f server/api/Dockerfile .

      - name: Push Docker image to Google Container Registry
        run: |
          docker push europe-west1-docker.pkg.dev/paper-lobster/paper-shop-repo/paper-shop-api-server:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.GCLOUD_SERVICE_NAME }} \
          --image europe-west1-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/paper-shop-repo/${{ secrets.GCLOUD_SERVICE_NAME }} \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated \
          --set-env-vars CLOUD_SQL_CONNECTION_NAME=${{ secrets.GCLOUD_SQL_CONNECTION_NAME }} \
          --set-env-vars DB_USER=${{ secrets.GCLOUD_DB_USER }} \
          --set-env-vars DB_PASSWORD=${{ secrets.GCLOUD_DB_PASSWORD }} \
          --set-env-vars DB_NAME=${{ secrets.GCLOUD_DB_NAME }} \
          --add-cloudsql-instances ${{ secrets.GCLOUD_SQL_CONNECTION_NAME }} \